/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.frutaria;

import java.awt.EventQueue;
import java.awt.event.ActionEvent;
import java.util.logging.Level;
import java.util.logging.Logger;

import javax.swing.JButton;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import javax.swing.JTable;
import javax.swing.JTextField;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;

import model.bean.Fruta;
import model.dao.FrutaDAO;

/**
 *
 * @author victor
 */
public class CadastrarFrutas extends javax.swing.JFrame {
	private static final long serialVersionUID = 1L;

	FrutaDAO dao = new FrutaDAO();

	ModelFrutas model = new ModelFrutas();

	/**
	 * Creates new form CadastrarFrutas
	 */
	public CadastrarFrutas() {
		initComponents();
		TxtBuscarFrutas.setText("Nome da fruta");
		TbCadastro.setModel(model);
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
	// <editor-fold defaultstate="collapsed" desc="Generated
	// Code">//GEN-BEGIN:initComponents
	private void initComponents() {

		HeaderCadastrarFrutas = new javax.swing.JLabel();
		jPanel1 = new javax.swing.JPanel();
		TxtEstoque = new javax.swing.JTextField();
		jLabel2 = new javax.swing.JLabel();
		TxtBuscarFrutas = new javax.swing.JTextField();
		jLabel3 = new javax.swing.JLabel();
		BtnSalvar = new javax.swing.JButton();
		TxtValor = new javax.swing.JTextField();
		jLabel4 = new javax.swing.JLabel();
		jScrollPane1 = new javax.swing.JScrollPane();
		TbCadastro = new javax.swing.JTable();
		BtnAtualizar = new javax.swing.JButton();
		TxtNome1 = new javax.swing.JTextField();
		BtnBuscar = new javax.swing.JButton();
		jToolBar1 = new javax.swing.JToolBar();
		jButton1 = new javax.swing.JButton();
		VoltarHome = new javax.swing.JButton();

		setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
		setTitle("Futaria Pacovan");

		HeaderCadastrarFrutas.setBackground(new java.awt.Color(255, 255, 255));
		HeaderCadastrarFrutas.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
		HeaderCadastrarFrutas.setForeground(new java.awt.Color(0, 0, 0));
		HeaderCadastrarFrutas.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
		HeaderCadastrarFrutas.setText("CADASTRO DE FRUTAS");

		jPanel1.setBackground(new java.awt.Color(255, 255, 255));
		jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

		TxtEstoque.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				TxtEstoqueActionPerformed(evt);
			}
		});

		jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
		jLabel2.setForeground(new java.awt.Color(0, 0, 0));
		jLabel2.setText("Valor:");

		TxtBuscarFrutas.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				TxtBuscarFrutasActionPerformed(evt);
			}
		});

		jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
		jLabel3.setForeground(new java.awt.Color(0, 0, 0));
		jLabel3.setText("Nome:");

		BtnSalvar.setBackground(new java.awt.Color(0, 51, 255));
		BtnSalvar.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
		BtnSalvar.setForeground(new java.awt.Color(255, 255, 255));
		BtnSalvar.setText("Salvar");
		BtnSalvar.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				BtnSalvarActionPerformed(evt);
			}
		});

		TxtValor.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				TxtValorActionPerformed(evt);
			}
		});

		jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
		jLabel4.setForeground(new java.awt.Color(0, 0, 0));
		jLabel4.setText("Estoque:");

		TbCadastro
				.setModel(new javax.swing.table.DefaultTableModel(
						new Object[][] { { null, null, null, null }, { null, null, null, null },
								{ null, null, null, null }, { null, null, null, null } },
						new String[] { "Codigo", "Nome", "Valor", "Estoque" }));
		jScrollPane1.setViewportView(TbCadastro);

		BtnAtualizar.setBackground(new java.awt.Color(0, 51, 255));
		BtnAtualizar.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
		BtnAtualizar.setForeground(new java.awt.Color(255, 255, 255));
		BtnAtualizar.setText("Atualizar");
		BtnAtualizar.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				BtnAtualizarActionPerformed(evt);
			}
		});

		TxtNome1.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				TxtNome1ActionPerformed(evt);
			}
		});

		BtnBuscar.setBackground(new java.awt.Color(0, 0, 204));
		BtnBuscar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
		BtnBuscar.setForeground(new java.awt.Color(255, 255, 255));
		BtnBuscar.setText("Buscar");
		BtnBuscar.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				BtnBuscarActionPerformed(evt);
			}
		});

		javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
		jPanel1.setLayout(jPanel1Layout);
		jPanel1Layout.setHorizontalGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(jPanel1Layout.createSequentialGroup()
						.addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
								.addGroup(jPanel1Layout.createSequentialGroup()
										.addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
										.addComponent(BtnSalvar).addGap(31, 31, 31).addComponent(BtnAtualizar)
										.addGap(55, 55, 55))
								.addGroup(jPanel1Layout.createSequentialGroup().addGroup(jPanel1Layout
										.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
										.addGroup(jPanel1Layout.createSequentialGroup().addGap(68, 68, 68)
												.addGroup(jPanel1Layout
														.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
														.addGroup(jPanel1Layout
																.createParallelGroup(
																		javax.swing.GroupLayout.Alignment.LEADING)
																.addComponent(jLabel2,
																		javax.swing.GroupLayout.PREFERRED_SIZE, 48,
																		javax.swing.GroupLayout.PREFERRED_SIZE)
																.addComponent(jLabel3,
																		javax.swing.GroupLayout.PREFERRED_SIZE, 57,
																		javax.swing.GroupLayout.PREFERRED_SIZE))
														.addGroup(jPanel1Layout.createSequentialGroup()
																.addComponent(jLabel4,
																		javax.swing.GroupLayout.PREFERRED_SIZE, 57,
																		javax.swing.GroupLayout.PREFERRED_SIZE)
																.addGap(9, 9, 9))))
										.addGroup(javax.swing.GroupLayout.Alignment.TRAILING,
												jPanel1Layout.createSequentialGroup().addContainerGap()
														.addComponent(BtnBuscar).addPreferredGap(
																javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
										.addGroup(jPanel1Layout
												.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
												.addComponent(TxtValor, javax.swing.GroupLayout.DEFAULT_SIZE, 283,
														Short.MAX_VALUE)
												.addComponent(TxtEstoque, javax.swing.GroupLayout.DEFAULT_SIZE, 283,
														Short.MAX_VALUE)
												.addComponent(TxtBuscarFrutas, javax.swing.GroupLayout.DEFAULT_SIZE,
														283, Short.MAX_VALUE)
												.addComponent(TxtNome1))))
						.addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 511,
								javax.swing.GroupLayout.PREFERRED_SIZE)
						.addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)));
		jPanel1Layout.setVerticalGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(jPanel1Layout.createSequentialGroup().addGap(18, 18, 18).addGroup(jPanel1Layout
						.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
						.addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 283,
								javax.swing.GroupLayout.PREFERRED_SIZE)
						.addGroup(jPanel1Layout.createSequentialGroup()
								.addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
										.addComponent(TxtBuscarFrutas, javax.swing.GroupLayout.PREFERRED_SIZE, 33,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addComponent(BtnBuscar))
								.addGap(18, 18, 18)
								.addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
										.addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 27,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addComponent(TxtNome1, javax.swing.GroupLayout.PREFERRED_SIZE, 33,
												javax.swing.GroupLayout.PREFERRED_SIZE))
								.addGap(18, 18, 18)
								.addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
										.addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 27,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addComponent(TxtValor, javax.swing.GroupLayout.PREFERRED_SIZE, 33,
												javax.swing.GroupLayout.PREFERRED_SIZE))
								.addGap(18, 18, 18)
								.addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
										.addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 27,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addComponent(TxtEstoque, javax.swing.GroupLayout.PREFERRED_SIZE, 33,
												javax.swing.GroupLayout.PREFERRED_SIZE))
								.addGap(50, 50, 50)
								.addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
										.addComponent(BtnSalvar).addComponent(BtnAtualizar))))
						.addContainerGap(75, Short.MAX_VALUE)));

		jToolBar1.setRollover(true);

		jButton1.setBackground(new java.awt.Color(0, 0, 204));
		jButton1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
		jButton1.setForeground(new java.awt.Color(255, 255, 255));
		jButton1.setText("sair");
		jButton1.setFocusable(false);
		jButton1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
		jButton1.setMaximumSize(new java.awt.Dimension(50, 40));
		jButton1.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
		jButton1.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton1ActionPerformed(evt);
			}
		});
		jToolBar1.add(jButton1);

		VoltarHome.setBackground(new java.awt.Color(0, 0, 204));
		VoltarHome.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
		VoltarHome.setForeground(new java.awt.Color(255, 255, 255));
		VoltarHome.setText("Voltar");
		VoltarHome.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				VoltarHomeActionPerformed(evt);
			}
		});
		jToolBar1.add(VoltarHome);

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
		getContentPane().setLayout(layout);
		layout.setHorizontalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addComponent(HeaderCadastrarFrutas, javax.swing.GroupLayout.Alignment.TRAILING,
						javax.swing.GroupLayout.DEFAULT_SIZE, 966, Short.MAX_VALUE)
				.addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE,
						Short.MAX_VALUE)
				.addComponent(jToolBar1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE,
						Short.MAX_VALUE));
		layout.setVerticalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(layout.createSequentialGroup().addComponent(HeaderCadastrarFrutas)
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED,
								javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
						.addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 25,
								javax.swing.GroupLayout.PREFERRED_SIZE)
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED).addComponent(jPanel1,
								javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE,
								javax.swing.GroupLayout.PREFERRED_SIZE)));

		pack();
		setLocationRelativeTo(null);
	}// </editor-fold>//GEN-END:initComponents

	private void TxtEstoqueActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_TxtEstoqueActionPerformed
		// TODO add your handling code here:
	}// GEN-LAST:event_TxtEstoqueActionPerformed

	private void TxtBuscarFrutasActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_TxtBuscarFrutasActionPerformed
		// TODO add your handling code here:
	}// GEN-LAST:event_TxtBuscarFrutasActionPerformed

	private void TxtValorActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_TxtValorActionPerformed
		// TODO add your handling code here:
	}// GEN-LAST:event_TxtValorActionPerformed

	private void BtnSalvarActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_BtnSalvarActionPerformed
		String nomeFruta = TxtBuscarFrutas.getText();
		Double valorFruta = Double.parseDouble(TxtValor.getText());
		int estoqueFruta = Integer.parseInt(TxtEstoque.getText());

		Fruta fruta = new Fruta(nomeFruta, valorFruta, estoqueFruta);
		dao.create(fruta);

//        String codigo = TxtCodigo.getText();
//        String nome = TxtNome.getText();
//        int valor = Integer.parseInt(TxtValor.getText());
//        int estoque = Integer.parseInt(TxtEstoque.getText());

		this.model.cadastrarFrutas(fruta);

		LimparCampos();
	}// GEN-LAST:event_BtnSalvarActionPerformed

	private void VoltarHomeActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_VoltarHomeActionPerformed
		telaPrincipal tp = new telaPrincipal();
		this.dispose();
		tp.setVisible(true);
	}// GEN-LAST:event_VoltarHomeActionPerformed

	private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jButton1ActionPerformed
		this.dispose();
	}// GEN-LAST:event_jButton1ActionPerformed

	private void BtnAtualizarActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_BtnAtualizarActionPerformed
		// TODO add your handling code here:
	}// GEN-LAST:event_BtnAtualizarActionPerformed

	private void TxtNome1ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_TxtNome1ActionPerformed
		// TODO add your handling code here:
	}// GEN-LAST:event_TxtNome1ActionPerformed

	private void BtnBuscarActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_BtnBuscarActionPerformed
		String nome = TxtBuscarFrutas.getText();
		Fruta fruta = dao.buscarFrutaPorNome(nome);
		
		TxtNome1.setText(fruta.getNome());
		TxtValor.setText(String.valueOf(fruta.getValor()));
		TxtEstoque.setText(String.valueOf(fruta.getEstoque()));
	}

	public void LimparCampos() {
		TxtBuscarFrutas.setText("");
		TxtValor.setText("");
		TxtEstoque.setText("");
	}

	public boolean validarCampos(String codigo, String nome, Integer valor, Integer estoque) {
		if (codigo.trim().isEmpty() || nome.trim().isEmpty() || valor == null || estoque == null) {
			JOptionPane.showMessageDialog(this, "legal");
			return false;
		}
		return true;
	}

	/**
	 * @param args the command line arguments
	 */
	public static void main(String args[]) {
		/* Set the Nimbus look and feel */
		// <editor-fold defaultstate="collapsed" desc=" Look and feel setting code
		// (optional) ">
		/*
		 * If Nimbus (introduced in Java SE 6) is not available, stay with the default
		 * look and feel. For details see
		 * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
		 */
		try {
			for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
				if ("Nimbus".equals(info.getName())) {
					javax.swing.UIManager.setLookAndFeel(info.getClassName());
					break;
				}
			}
		} catch (ClassNotFoundException ex) {
			java.util.logging.Logger.getLogger(CadastrarFrutas.class.getName()).log(java.util.logging.Level.SEVERE,
					null, ex);
		} catch (InstantiationException ex) {
			java.util.logging.Logger.getLogger(CadastrarFrutas.class.getName()).log(java.util.logging.Level.SEVERE,
					null, ex);
		} catch (IllegalAccessException ex) {
			java.util.logging.Logger.getLogger(CadastrarFrutas.class.getName()).log(java.util.logging.Level.SEVERE,
					null, ex);
		} catch (javax.swing.UnsupportedLookAndFeelException ex) {
			java.util.logging.Logger.getLogger(CadastrarFrutas.class.getName()).log(java.util.logging.Level.SEVERE,
					null, ex);
		}
		// </editor-fold>

		/* Create and display the form */
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				new CadastrarFrutas().setVisible(true);
			}
		});
	}

	// Variables declaration - do not modify//GEN-BEGIN:variables
	private javax.swing.JButton BtnAtualizar;
	private javax.swing.JButton BtnBuscar;
	private javax.swing.JButton BtnSalvar;
	private javax.swing.JLabel HeaderCadastrarFrutas;
	private javax.swing.JTable TbCadastro;
	private javax.swing.JTextField TxtBuscarFrutas;
	private javax.swing.JTextField TxtEstoque;
	private javax.swing.JTextField TxtNome1;
	private javax.swing.JTextField TxtValor;
	private javax.swing.JButton VoltarHome;
	private javax.swing.JButton jButton1;
	private javax.swing.JLabel jLabel2;
	private javax.swing.JLabel jLabel3;
	private javax.swing.JLabel jLabel4;
	private javax.swing.JPanel jPanel1;
	private javax.swing.JScrollPane jScrollPane1;
	private javax.swing.JToolBar jToolBar1;
	// End of variables declaration//GEN-END:variables
}
