/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.frutaria;

import java.awt.EventQueue;
import java.awt.event.ActionEvent;
import java.util.logging.Level;
import java.util.logging.Logger;

import javax.swing.JButton;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import javax.swing.JTable;
import javax.swing.JTextField;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;

import model.bean.Fruta;
import model.dao.FrutaDAO;

/**
 *
 * @author victor
 */
public class CadastrarFrutas extends JFrame {

	private static final long serialVersionUID = 1L;

	ModelFrutas model = new ModelFrutas();

	/**
	 * Creates new form CadastrarFrutas
	 */
	public CadastrarFrutas() {
		initComponents();
		TbCadastro.setModel(model);

	}

	private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {
		// TODO add your handling code here:
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
	// <editor-fold defaultstate="collapsed" desc="Generated
	// Code">//GEN-BEGIN:initComponents
	private void initComponents() {

		HeaderCadastrarFrutas = new javax.swing.JLabel();
		jPanel1 = new javax.swing.JPanel();
		jLabel1 = new javax.swing.JLabel();
		TxtEstoque = new javax.swing.JTextField();
		TxtCodigo = new javax.swing.JTextField();
		jLabel2 = new javax.swing.JLabel();
		TxtNome = new javax.swing.JTextField();
		jLabel3 = new javax.swing.JLabel();
		BtnSalvar = new javax.swing.JButton();
		TxtValor = new javax.swing.JTextField();
		jLabel4 = new javax.swing.JLabel();
		jScrollPane1 = new javax.swing.JScrollPane();
		TbCadastro = new javax.swing.JTable();
		VoltarHome = new javax.swing.JButton();

		setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
		setTitle("Futaria Pacovan");

		HeaderCadastrarFrutas.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
		HeaderCadastrarFrutas.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
		HeaderCadastrarFrutas.setText("CADASTRO DE FRUTAS");

		jPanel1.setBackground(new java.awt.Color(204, 204, 204));
		jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

		jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
		jLabel1.setText("Codigo:");

		TxtEstoque.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				TxtEstoqueActionPerformed(evt);
			}
		});

		TxtCodigo.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				TxtCodigoActionPerformed(evt);
			}
		});

		jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
		jLabel2.setText("Valor:");

		TxtNome.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				TxtNomeActionPerformed(evt);
			}
		});

		jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
		jLabel3.setText("Nome:");

		BtnSalvar.setBackground(new java.awt.Color(0, 204, 0));
		BtnSalvar.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
		BtnSalvar.setForeground(new java.awt.Color(255, 255, 255));
		BtnSalvar.setText("Salvar");
		BtnSalvar.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				BtnSalvarActionPerformed(evt);
			}
		});

		TxtValor.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				TxtValorActionPerformed(evt);
			}
		});

		jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
		jLabel4.setText("Estoque:");

		TbCadastro
				.setModel(new javax.swing.table.DefaultTableModel(
						new Object[][] { { null, null, null, null }, { null, null, null, null },
								{ null, null, null, null }, { null, null, null, null } },
						new String[] { "Codigo", "Nome", "Valor", "Estoque" }));
		jScrollPane1.setViewportView(TbCadastro);

		VoltarHome.setBackground(new java.awt.Color(0, 204, 0));
		VoltarHome.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
		VoltarHome.setForeground(new java.awt.Color(255, 255, 255));
		VoltarHome.setText("Voltar");
		VoltarHome.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				VoltarHomeActionPerformed(evt);
			}
		});

		javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
		jPanel1.setLayout(jPanel1Layout);
		jPanel1Layout.setHorizontalGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(jPanel1Layout.createSequentialGroup().addGroup(jPanel1Layout
						.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(jPanel1Layout.createSequentialGroup().addGap(43, 43, 43).addGroup(jPanel1Layout
								.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
								.addGroup(javax.swing.GroupLayout.Alignment.TRAILING,
										jPanel1Layout.createSequentialGroup()
												.addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 57,
														javax.swing.GroupLayout.PREFERRED_SIZE)
												.addGap(18, 18, 18)
												.addComponent(TxtValor, javax.swing.GroupLayout.PREFERRED_SIZE, 271,
														javax.swing.GroupLayout.PREFERRED_SIZE))
								.addGroup(javax.swing.GroupLayout.Alignment.TRAILING,
										jPanel1Layout.createSequentialGroup()
												.addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 57,
														javax.swing.GroupLayout.PREFERRED_SIZE)
												.addGap(18, 18, 18).addComponent(TxtNome,
														javax.swing.GroupLayout.PREFERRED_SIZE, 272,
														javax.swing.GroupLayout.PREFERRED_SIZE))
								.addGroup(javax.swing.GroupLayout.Alignment.TRAILING,
										jPanel1Layout.createSequentialGroup()
												.addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 57,
														javax.swing.GroupLayout.PREFERRED_SIZE)
												.addGap(18, 18, 18).addComponent(TxtEstoque,
														javax.swing.GroupLayout.PREFERRED_SIZE, 271,
														javax.swing.GroupLayout.PREFERRED_SIZE))
								.addGroup(javax.swing.GroupLayout.Alignment.TRAILING,
										jPanel1Layout.createSequentialGroup().addComponent(VoltarHome)
												.addGap(43, 43, 43).addComponent(BtnSalvar).addGap(51, 51, 51))))
						.addGroup(jPanel1Layout.createSequentialGroup().addGap(44, 44, 44)
								.addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 57,
										javax.swing.GroupLayout.PREFERRED_SIZE)
								.addGap(18, 18, 18).addComponent(TxtCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 272,
										javax.swing.GroupLayout.PREFERRED_SIZE)))
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED,
								javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
						.addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 511,
								javax.swing.GroupLayout.PREFERRED_SIZE)
						.addContainerGap()));
		jPanel1Layout.setVerticalGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(jPanel1Layout.createSequentialGroup().addGroup(jPanel1Layout
						.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(jPanel1Layout.createSequentialGroup().addGap(37, 37, 37)
								.addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
										.addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 27,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addComponent(TxtCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 33,
												javax.swing.GroupLayout.PREFERRED_SIZE))
								.addGap(31, 31, 31)
								.addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
										.addComponent(TxtNome, javax.swing.GroupLayout.PREFERRED_SIZE, 33,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 27,
												javax.swing.GroupLayout.PREFERRED_SIZE))
								.addGap(26, 26, 26)
								.addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
										.addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 27,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addComponent(TxtValor, javax.swing.GroupLayout.PREFERRED_SIZE, 33,
												javax.swing.GroupLayout.PREFERRED_SIZE))
								.addGap(26, 26, 26)
								.addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
										.addComponent(TxtEstoque, javax.swing.GroupLayout.PREFERRED_SIZE, 33,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 27,
												javax.swing.GroupLayout.PREFERRED_SIZE))
								.addGap(42, 42, 42)
								.addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
										.addComponent(BtnSalvar).addComponent(VoltarHome)))
						.addGroup(jPanel1Layout.createSequentialGroup().addGap(29, 29, 29).addComponent(jScrollPane1,
								javax.swing.GroupLayout.PREFERRED_SIZE, 283, javax.swing.GroupLayout.PREFERRED_SIZE)))
						.addContainerGap(56, Short.MAX_VALUE)));

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
		getContentPane().setLayout(layout);
		layout.setHorizontalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addComponent(HeaderCadastrarFrutas, javax.swing.GroupLayout.Alignment.TRAILING,
						javax.swing.GroupLayout.DEFAULT_SIZE, 966, Short.MAX_VALUE)
				.addGroup(layout.createSequentialGroup().addContainerGap().addComponent(jPanel1,
						javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
						.addContainerGap()));
		layout.setVerticalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(layout.createSequentialGroup()
						.addComponent(HeaderCadastrarFrutas, javax.swing.GroupLayout.PREFERRED_SIZE, 33,
								javax.swing.GroupLayout.PREFERRED_SIZE)
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
						.addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE,
								javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
						.addGap(0, 9, Short.MAX_VALUE)));

		pack();
		setLocationRelativeTo(null);
	}// </editor-fold>//GEN-END:initComponents

	private void TxtEstoqueActionPerformed(ActionEvent evt) {// GEN-FIRST:event_TxtEstoqueActionPerformed
		// TODO add your handling code here:
	}// GEN-LAST:event_TxtEstoqueActionPerformed

	private void TxtCodigoActionPerformed(ActionEvent evt) {// GEN-FIRST:event_TxtCodigoActionPerformed
		// TODO add your handling code here:
	}// GEN-LAST:event_TxtCodigoActionPerformed

	private void TxtNomeActionPerformed(ActionEvent evt) {// GEN-FIRST:event_TxtNomeActionPerformed
		// TODO add your handling code here:
	}// GEN-LAST:event_TxtNomeActionPerformed

	private void TxtValorActionPerformed(ActionEvent evt) {// GEN-FIRST:event_TxtValorActionPerformed
		// TODO add your handling code here:
	}// GEN-LAST:event_TxtValorActionPerformed

	private void BtnSalvarActionPerformed(ActionEvent evt) {// GEN-FIRST:event_BtnSalvarActionPerformed
		int id = Integer.parseInt(TxtCodigo.getText());
		String nomeFruta = TxtNome.getText();
		Double valorFruta = Double.parseDouble(TxtValor.getText());
		int estoqueFruta = Integer.parseInt(TxtEstoque.getText());

		Fruta fruta = new Fruta(id, nomeFruta, valorFruta, estoqueFruta);
		FrutaDAO dao = new FrutaDAO();
		dao.create(fruta);

//        String codigo = TxtCodigo.getText();
//        String nome = TxtNome.getText();
//        int valor = Integer.parseInt(TxtValor.getText());
//        int estoque = Integer.parseInt(TxtEstoque.getText());
		Fruta f = null;

		this.model.cadastrarFrutas(fruta);

		LimparCampos();
	}// GEN-LAST:event_BtnSalvarActionPerformed

	private void VoltarHomeActionPerformed(ActionEvent evt) {// GEN-FIRST:event_VoltarHomeActionPerformed
		telaPrincipal tp = new telaPrincipal();
		this.dispose();
		tp.setVisible(true);
	}// GEN-LAST:event_VoltarHomeActionPerformed

	public void LimparCampos() {
		TxtCodigo.setText("");
		TxtNome.setText("");
		TxtValor.setText("");
		TxtEstoque.setText("");
	}

	public boolean validarCampos(String codigo, String nome, Integer valor, Integer estoque) {
		if (codigo.trim().isEmpty() || nome.trim().isEmpty() || valor == null || estoque == null) {
			JOptionPane.showMessageDialog(this, "fodase");
			return false;
		}
		return true;
	}

	/**
	 * @param args the command line arguments
	 */
	public static void main(String args[]) {
		/* Set the Nimbus look and feel */
		// <editor-fold defaultstate="collapsed" desc=" Look and feel setting code
		// (optional) ">
		/*
		 * If Nimbus (introduced in Java SE 6) is not available, stay with the default
		 * look and feel. For details see
		 * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
		 */
		try {
			for (UIManager.LookAndFeelInfo info : UIManager.getInstalledLookAndFeels()) {
				if ("Nimbus".equals(info.getName())) {
					UIManager.setLookAndFeel(info.getClassName());
					break;
				}
			}
		} catch (ClassNotFoundException ex) {
			Logger.getLogger(CadastrarFrutas.class.getName()).log(Level.SEVERE, null, ex);
		} catch (InstantiationException ex) {
			Logger.getLogger(CadastrarFrutas.class.getName()).log(Level.SEVERE, null, ex);
		} catch (IllegalAccessException ex) {
			Logger.getLogger(CadastrarFrutas.class.getName()).log(Level.SEVERE, null, ex);
		} catch (UnsupportedLookAndFeelException ex) {
			Logger.getLogger(CadastrarFrutas.class.getName()).log(Level.SEVERE, null, ex);
		}
		// </editor-fold>

		/* Create and display the form */
		EventQueue.invokeLater(new Runnable() {
			public void run() {
				new CadastrarFrutas().setVisible(true);
			}
		});
	}

	// Variables declaration - do not modify//GEN-BEGIN:variables
	private JButton BtnSalvar;
	private JLabel HeaderCadastrarFrutas;
	private JTable TbCadastro;
	private JTextField TxtCodigo;
	private JTextField TxtEstoque;
	private JTextField TxtNome;
	private JTextField TxtValor;
	private JButton VoltarHome;
	private JLabel jLabel1;
	private JLabel jLabel2;
	private JLabel jLabel3;
	private JLabel jLabel4;
	private JPanel jPanel1;
	private JScrollPane jScrollPane1;
	// End of variables declaration//GEN-END:variables
}
