/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.frutaria;

import model.bean.CompraFruta;
import model.bean.Fruta;
import model.dao.CompraDAO;
import model.dao.FrutaDAO;

/**
 *
 * @author victor
 */
public class ComprarFrutas extends javax.swing.JFrame {

	private static final long serialVersionUID = 1L;

	ModelFrutas model = new ModelFrutas();


	public ComprarFrutas() {
		initComponents();
		TblComprarFrutas.setModel(model);
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
	// <editor-fold defaultstate="collapsed" desc="Generated
	// Code">//GEN-BEGIN:initComponents
	private void initComponents() {

		jPanel1 = new javax.swing.JPanel();
		jScrollPane1 = new javax.swing.JScrollPane();
		TblComprarFrutas = new javax.swing.JTable();
		jLabel1 = new javax.swing.JLabel();
		jLabel2 = new javax.swing.JLabel();
		TxtCpf = new javax.swing.JTextField();
		jLabel3 = new javax.swing.JLabel();
		TxtQuantComprar = new javax.swing.JTextField();
		jLabel4 = new javax.swing.JLabel();
		TxtValorComprar = new javax.swing.JTextField();
		jButton1 = new javax.swing.JButton();
		jButton2 = new javax.swing.JButton();
		jLabel5 = new javax.swing.JLabel();
		TxtNome = new javax.swing.JTextField();

		setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
		setResizable(false);

		jPanel1.setBackground(new java.awt.Color(204, 204, 204));
		jPanel1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

		TblComprarFrutas.setModel(new javax.swing.table.DefaultTableModel(new Object[][] { { null, null, null },
				{ null, null, null }, { null, null, null }, { null, null, null } },
				new String[] { "Title 1", "Title 2", "Title 3" }));
		jScrollPane1.setViewportView(TblComprarFrutas);

		jLabel1.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
		jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
		jLabel1.setText("BOAS COMPRAS!!!");

		jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
		jLabel2.setText("CPF:");

		TxtCpf.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				TxtCpfActionPerformed(evt);
			}
		});

		jLabel3.setText("QUANTIDADE:");

		TxtQuantComprar.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				TxtQuantComprarActionPerformed(evt);
			}
		});

		jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
		jLabel4.setText("VALOR:");

		TxtValorComprar.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				TxtValorComprarActionPerformed(evt);
			}
		});

		jButton1.setBackground(new java.awt.Color(0, 204, 0));
		jButton1.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
		jButton1.setText("MANDAR P/ CARRINHO");
		jButton1.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton1ActionPerformed(evt);
			}
		});

		jButton2.setBackground(new java.awt.Color(0, 204, 0));
		jButton2.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
		jButton2.setText("VOLTAR P/ HOME");
		jButton2.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton2ActionPerformed(evt);
			}
		});

		jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
		jLabel5.setText("NOME:");

		javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
		jPanel1.setLayout(jPanel1Layout);
		jPanel1Layout.setHorizontalGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(jPanel1Layout.createSequentialGroup().addGroup(jPanel1Layout
						.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(jPanel1Layout.createSequentialGroup().addGap(152, 152, 152).addComponent(jLabel1,
								javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE))
						.addGroup(jPanel1Layout.createSequentialGroup().addGap(70, 70, 70)
								.addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
										.addComponent(jButton2)
										.addGroup(jPanel1Layout
												.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
												.addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING,
														javax.swing.GroupLayout.DEFAULT_SIZE,
														javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
												.addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 100,
														javax.swing.GroupLayout.PREFERRED_SIZE)
												.addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING,
														javax.swing.GroupLayout.DEFAULT_SIZE, 115, Short.MAX_VALUE)))
								.addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
										.addGroup(javax.swing.GroupLayout.Alignment.TRAILING,
												jPanel1Layout.createSequentialGroup().addGap(81, 81, 81)
														.addComponent(jButton1))
										.addGroup(jPanel1Layout.createSequentialGroup().addGap(18, 18, 18)
												.addGroup(jPanel1Layout
														.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING,
																false)
														.addComponent(TxtCpf, javax.swing.GroupLayout.DEFAULT_SIZE, 248,
																Short.MAX_VALUE)
														.addComponent(TxtValorComprar,
																javax.swing.GroupLayout.DEFAULT_SIZE, 248,
																Short.MAX_VALUE)
														.addComponent(TxtQuantComprar,
																javax.swing.GroupLayout.DEFAULT_SIZE, 248,
																Short.MAX_VALUE)
														.addComponent(TxtNome)))))
						.addGroup(jPanel1Layout.createSequentialGroup().addGap(113, 113, 113).addComponent(jLabel5,
								javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)))
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 51, Short.MAX_VALUE)
						.addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 461,
								javax.swing.GroupLayout.PREFERRED_SIZE)
						.addContainerGap()));
		jPanel1Layout
				.setVerticalGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
								.addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 32,
										javax.swing.GroupLayout.PREFERRED_SIZE)
								.addGap(32, 32, 32)
								.addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
										.addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 278,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addGroup(jPanel1Layout.createSequentialGroup()
												.addGroup(jPanel1Layout
														.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
														.addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE,
																22, javax.swing.GroupLayout.PREFERRED_SIZE)
														.addComponent(TxtNome, javax.swing.GroupLayout.PREFERRED_SIZE,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																javax.swing.GroupLayout.PREFERRED_SIZE))
												.addGap(18, 18, 18)
												.addGroup(jPanel1Layout
														.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
														.addComponent(jLabel2).addComponent(TxtCpf,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																javax.swing.GroupLayout.PREFERRED_SIZE))
												.addGap(18, 18, 18)
												.addGroup(jPanel1Layout
														.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
														.addComponent(jLabel3).addComponent(TxtQuantComprar,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																javax.swing.GroupLayout.PREFERRED_SIZE))
												.addGap(18, 18, 18)
												.addGroup(jPanel1Layout
														.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
														.addComponent(jLabel4).addComponent(TxtValorComprar,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																javax.swing.GroupLayout.PREFERRED_SIZE))
												.addGap(59, 59, 59)
												.addGroup(jPanel1Layout
														.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
														.addComponent(jButton1).addComponent(jButton2))))
								.addContainerGap(38, Short.MAX_VALUE)));

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
		getContentPane().setLayout(layout);
		layout.setHorizontalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addComponent(
				jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE));
		layout.setVerticalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(layout.createSequentialGroup()
						.addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE,
								javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
						.addGap(0, 14, Short.MAX_VALUE)));

		pack();
		setLocationRelativeTo(null);
	}// </editor-fold>//GEN-END:initComponents

	private void TxtCpfActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_TxtCpfActionPerformed
		// TODO add your handling code here:
	}// GEN-LAST:event_TxtCpfActionPerformed

	private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jButton1ActionPerformed

		String nome = TxtNome.getText();
		String cpf = TxtCpf.getText();
		Integer quantidade = Integer.parseInt(TxtQuantComprar.getText());
		Double valor = Double.parseDouble(TxtValorComprar.getText());

		FrutaDAO dao = new FrutaDAO();

		Fruta fruta = dao.buscarFrutaPorNome(nome);
		fruta.atualizarEstoque(quantidade);

		dao.update(fruta);

		CompraDAO compraDao = new CompraDAO();
		CompraFruta compra = new CompraFruta();
		
		Double subTotal = valor * quantidade;
		
		compra.setCpf(cpf);
		
		if(compraDao.existeCompraNaoFinalizadoComCpf(cpf)) {
			compra = compraDao.buscarCompraNaoFinalizada(cpf);
			compra.atualizarQuantidade(quantidade);
			compra.atualizarValorTotal(subTotal);
			compraDao.update(compra);
			
		} else {
			compra.setCompraFinalizada(false);
			compra.setQuantidadeComprada(quantidade);
			compra.setValorTotal(subTotal);
			compraDao.create(compra);
		}
		
		limparCampos();
	}

	private void limparCampos() {
		TxtNome.setText("");
		TxtQuantComprar.setText("");
		TxtValorComprar.setText("");
	}

	private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jButton2ActionPerformed
		telaPrincipal tp = new telaPrincipal();
		this.dispose();
		tp.setVisible(true);
	}// GEN-LAST:event_jButton2ActionPerformed

	private void TxtValorComprarActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_TxtValorComprarActionPerformed
		// TODO add your handling code here:
	}// GEN-LAST:event_TxtValorComprarActionPerformed

	private void TxtQuantComprarActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_TxtQuantComprarActionPerformed
		// TODO add your handling code here:
	}// GEN-LAST:event_TxtQuantComprarActionPerformed

	/**
	 * @param args the command line arguments
	 */
	public static void main(String args[]) {
		/* Set the Nimbus look and feel */
		// <editor-fold defaultstate="collapsed" desc=" Look and feel setting code
		// (optional) ">
		/*
		 * If Nimbus (introduced in Java SE 6) is not available, stay with the default
		 * look and feel. For details see
		 * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
		 */
		try {
			for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
				if ("Nimbus".equals(info.getName())) {
					javax.swing.UIManager.setLookAndFeel(info.getClassName());
					break;
				}
			}
		} catch (ClassNotFoundException ex) {
			java.util.logging.Logger.getLogger(ComprarFrutas.class.getName()).log(java.util.logging.Level.SEVERE, null,
					ex);
		} catch (InstantiationException ex) {
			java.util.logging.Logger.getLogger(ComprarFrutas.class.getName()).log(java.util.logging.Level.SEVERE, null,
					ex);
		} catch (IllegalAccessException ex) {
			java.util.logging.Logger.getLogger(ComprarFrutas.class.getName()).log(java.util.logging.Level.SEVERE, null,
					ex);
		} catch (javax.swing.UnsupportedLookAndFeelException ex) {
			java.util.logging.Logger.getLogger(ComprarFrutas.class.getName()).log(java.util.logging.Level.SEVERE, null,
					ex);
		}
		// </editor-fold>

		/* Create and display the form */
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				new ComprarFrutas().setVisible(true);
			}
		});
	}

	// Variables declaration - do not modify//GEN-BEGIN:variables
	private javax.swing.JTable TblComprarFrutas;
	private javax.swing.JTextField TxtCpf;
	private javax.swing.JTextField TxtNome;
	private javax.swing.JTextField TxtQuantComprar;
	private javax.swing.JTextField TxtValorComprar;
	private javax.swing.JButton jButton1;
	private javax.swing.JButton jButton2;
	private javax.swing.JLabel jLabel1;
	private javax.swing.JLabel jLabel2;
	private javax.swing.JLabel jLabel3;
	private javax.swing.JLabel jLabel4;
	private javax.swing.JLabel jLabel5;
	private javax.swing.JPanel jPanel1;
	private javax.swing.JScrollPane jScrollPane1;
	// End of variables declaration//GEN-END:variables
}
