/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.frutaria;

import javax.swing.JOptionPane;

/**
 *
 * @author victor
 */
public class telaPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form telaPrincipal
     */
    public telaPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PainelLogo = new javax.swing.JPanel();
        LogoPacovan = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jToolBar1 = new javax.swing.JToolBar();
        jMenuBar1 = new javax.swing.JMenuBar();
        MenuFutas = new javax.swing.JMenu();
        ItemComprar = new javax.swing.JMenuItem();
        Cadastraritem = new javax.swing.JMenu();
        ClienteCadas = new javax.swing.JMenuItem();
        LoginFuncionario = new javax.swing.JMenuItem();
        MenuOutro = new javax.swing.JMenu();
        SairTela = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Frutaria pacovan");
        setResizable(false);

        PainelLogo.setBackground(new java.awt.Color(204, 204, 204));
        PainelLogo.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        LogoPacovan.setFont(new java.awt.Font("Showcard Gothic", 2, 48)); // NOI18N
        LogoPacovan.setForeground(new java.awt.Color(255, 153, 0));
        LogoPacovan.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LogoPacovan.setText("PACOVAN");

        jLabel3.setFont(new java.awt.Font("Showcard Gothic", 2, 48)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 102, 0));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("FRUTARIA");

        javax.swing.GroupLayout PainelLogoLayout = new javax.swing.GroupLayout(PainelLogo);
        PainelLogo.setLayout(PainelLogoLayout);
        PainelLogoLayout.setHorizontalGroup(
            PainelLogoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PainelLogoLayout.createSequentialGroup()
                .addContainerGap(145, Short.MAX_VALUE)
                .addComponent(LogoPacovan, javax.swing.GroupLayout.PREFERRED_SIZE, 523, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(299, 299, 299))
            .addGroup(PainelLogoLayout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 558, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        PainelLogoLayout.setVerticalGroup(
            PainelLogoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PainelLogoLayout.createSequentialGroup()
                .addGap(96, 96, 96)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(LogoPacovan, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(164, Short.MAX_VALUE))
        );

        jToolBar1.setBackground(new java.awt.Color(255, 255, 255));
        jToolBar1.setRollover(true);

        MenuFutas.setText("Comprar");
        MenuFutas.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        MenuFutas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuFutasActionPerformed(evt);
            }
        });

        ItemComprar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        ItemComprar.setText("Frutas");
        ItemComprar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ItemComprarActionPerformed(evt);
            }
        });
        MenuFutas.add(ItemComprar);

        jMenuBar1.add(MenuFutas);

        Cadastraritem.setText("Cadastrar");
        Cadastraritem.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N

        ClienteCadas.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        ClienteCadas.setText("Cliente");
        ClienteCadas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ClienteCadasActionPerformed(evt);
            }
        });
        Cadastraritem.add(ClienteCadas);

        LoginFuncionario.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        LoginFuncionario.setText("Login");
        LoginFuncionario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LoginFuncionarioActionPerformed(evt);
            }
        });
        Cadastraritem.add(LoginFuncionario);

        jMenuBar1.add(Cadastraritem);

        MenuOutro.setText("Outros");
        MenuOutro.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N

        SairTela.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        SairTela.setText("Sair");
        SairTela.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SairTelaActionPerformed(evt);
            }
        });
        MenuOutro.add(SairTela);

        jMenuBar1.add(MenuOutro);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jToolBar1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(PainelLogo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(PainelLogo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void LoginFuncionarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LoginFuncionarioActionPerformed
      CadastrarFuncionario Cadfunc = new CadastrarFuncionario();
      this.dispose();
      Cadfunc.setVisible(true);
    }//GEN-LAST:event_LoginFuncionarioActionPerformed

    private void MenuFutasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuFutasActionPerformed
      
    }//GEN-LAST:event_MenuFutasActionPerformed

    private void ItemComprarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ItemComprarActionPerformed
       ComprarFrutas cf = new ComprarFrutas();
       this.dispose();
       cf.setVisible(true);
    }//GEN-LAST:event_ItemComprarActionPerformed

    private void SairTelaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SairTelaActionPerformed
       this.dispose();
    }//GEN-LAST:event_SairTelaActionPerformed

    private void ClienteCadasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ClienteCadasActionPerformed
      TelaCadastroCliente tcc = new TelaCadastroCliente();
      this.dispose();
      tcc.setVisible(true);
    }//GEN-LAST:event_ClienteCadasActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(telaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(telaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(telaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(telaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new telaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu Cadastraritem;
    private javax.swing.JMenuItem ClienteCadas;
    private javax.swing.JMenuItem ItemComprar;
    private javax.swing.JMenuItem LoginFuncionario;
    private javax.swing.JLabel LogoPacovan;
    private javax.swing.JMenu MenuFutas;
    private javax.swing.JMenu MenuOutro;
    private javax.swing.JPanel PainelLogo;
    private javax.swing.JMenuItem SairTela;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JToolBar jToolBar1;
    // End of variables declaration//GEN-END:variables
}
